version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transactions_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/transactions_db

volumes:
  db_data:
